POST http://localhost/resolvendo_problema/problema_api/problema_api/problema.php
Content-Type: application/json

{
    "nome": "João victor",
    "email": "joa.treeex@ample.com",
    "senha": "Senha_123",
    "telefone": "1234567891",
    "endereco": "Rua A, 123",
    "estado": "SP",
    "data_nascimento": "1990-01-01"
}
###
GET http://localhost/resolvendo_problema/problema_api/problema_api/problema.php

###
GET http://localhost/resolvendo_problema/problema_api/problema_api/problema.php?id=9bd3-1a-0e-8f-6a469


###
DELETE http://localhost/resolvendo_problema/problema_api/problema_api/problema.php?id=0a29-22-77-11-ab4365