POST http://localhost/resolvendo_problema/problema_api/problema_api/problema.php
Content-Type: application/json

{
    "nome": "João victor",
    "email": "joa.treerex@ample.com",
    "senha": "Senha_123",
    "telefone": "1234567891",
    "endereco": "Rua A, 123",
    "estado": "SP",
    "data_nascimento": "1990-01-01"
}
###
GET http://localhost/resolvendo_problema/problema_api/problema_api/problema.php 

###
GET http://localhost/resolvendo_problema/problema_api/problema_api/problema.php?id=$2y$10$.pEfpV8uWfXHUd7aVwrM8epvY4Bx4I.GefUigYW8IJm3F5mxOQBxm 


###
DELETE http://localhost/resolvendo_problema/problema_api/problema_api/problema.php